<a href="https://colab.research.google.com/github/ujwaljain506-hash/anime-recommender/blob/main/day2_tfidf_vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/anime-dataset-2023.csv')
print("File Loaded")

File Loaded

What is TF-IDF?

The full name is Term Frequency - Inverse Document Frequency. Sounds scary, but the idea is simple.
Imagine you're comparing anime by their genres. Two things matter:
TF (Term Frequency): How often does a genre appear in THIS anime's description? If "Action" appears, it gets a score.
IDF (Inverse Document Frequency): How rare is this genre across ALL anime? If "Action" appears in 90% of all anime — it's not very useful for telling anime apart. But if "Psychological" only appears in 5% of anime — it's a very distinctive, meaningful genre.

In [9]:
df['Genres'].isnull().sum()

np.int64(0)

In [10]:
df[df['Genres']=='Unkown']['Genres'].count()

np.int64(0)

In [11]:
df['Genres'].value_counts().tail(10)

Genres
Comedy, Fantasy, Girls Love, Romance                            1
Avant Garde, Mystery                                            1
Action, Adventure, Boys Love, Fantasy, Mystery, Supernatural    1
Sports, Suspense                                                1
Adventure, Comedy, Mystery, Romance                             1
Adventure, Comedy, Drama, Romance, Sci-Fi                       1
Boys Love, Comedy, Supernatural                                 1
Fantasy, Suspense, Ecchi                                        1
Fantasy, Romance, Slice of Life, Supernatural                   1
Romance, Suspense                                               1
Name: count, dtype: int64

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['Genres'])

print(tfidf_matrix.shape)

(24905, 28)

In [14]:
print(tfidf.get_feature_names_out())

['action' 'adventure' 'avant' 'award' 'boys' 'comedy' 'drama' 'ecchi'
 'erotica' 'fantasy' 'fi' 'garde' 'girls' 'gourmet' 'hentai' 'horror'
 'life' 'love' 'mystery' 'of' 'romance' 'sci' 'slice' 'sports'
 'supernatural' 'suspense' 'unknown' 'winning']

In [15]:
df['Genres'] = df['Genres'].str.replace(' ,', ',').str.replace(', ',',').str.replace(' ', '_').str.replace('-', '_')

In [16]:
df['Genres'].head(10)

0          Action,Award_Winning,Sci_Fi
1                        Action,Sci_Fi
2              Action,Adventure,Sci_Fi
3    Action,Drama,Mystery,Supernatural
4       Adventure,Fantasy,Supernatural
5                               Sports
6                 Comedy,Drama,Romance
7          Comedy,Slice_of_Life,Sports
8                         Action,Drama
9               Drama,Mystery,Suspense
Name: Genres, dtype: object

In [17]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['Genres'])
print(tfidf.get_feature_names_out())

['action' 'adventure' 'avant_garde' 'award_winning' 'boys_love' 'comedy'
 'drama' 'ecchi' 'erotica' 'fantasy' 'girls_love' 'gourmet' 'hentai'
 'horror' 'mystery' 'romance' 'sci_fi' 'slice_of_life' 'sports'
 'supernatural' 'suspense' 'unknown']

In [18]:
df = df[df['Genres'] != 'unknown']
print(df.shape)

(24905, 24)

In [19]:
df[df['Genres'].str.contains('unknown')].shape

(0, 24)

In [20]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['Genres'])
print(tfidf_matrix.shape)

(24905, 22)